services:
  backend:
    build: ./backend
    container_name: scrubber-backend
    volumes:
      - downloads_data:/downloads
    restart: unless-stopped
    hostname: "backend"

  frontend:
    build: ./frontend
    container_name: scrubber-frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
      - downloads_data:/downloads:ro
    ports:
      - "8081:8080"
    depends_on:
      - backend
    hostname: "frontend"

  tailscale:
    image: tailscale/tailscale:latest
    container_name: scrubber-tailscale
    cap_add:
      - net_admin
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_HOSTNAME=yt
    volumes:
      - ./config:/config:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    depends_on:
      - frontend

volumes:
  downloads_data:
